config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'

  resources :businesses do
    resources :employees
    resources :perks, only: [:new, :create]
    resources :products do
      resources :perks, only: [:show, :new, :edit, :update, :destroy]
    end
    resources :perk_templates, only: [:new, :create]
  end

  resources :users, except: [:new, :create, :index, :show]

  resources :purchases, except: [:edit, :update, :destroy]

  get 'users/:id/validate', to: 'users#validate', as: 'validation_page'
  get 'discover', to: 'pages#discover'

  get 'business_dashboard', to: 'pages#business_dashboard', as: 'business_dashboard'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard_page'

  get 'welcome', to: 'pages#welcome', as: 'welcome_page'

  get 'businesses/:id/new_connection', to: 'businesses#new_connection', as: 'business_connection'

  get 'businesses/:id/filter_new_connection', to: 'businesses#filter_new_connection', as: 'filter_business_connection'


end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    @business.user_id = current_user.id
    @business.business_category_id = params[:business][:business_category_id]
    if @business.save
      redirect_to @business
    else
      # New should be in quotes not a key
      render "new"
    end
  end

  def show
    @business = Business.find(params[:id])
    @user = current_user
  end

  def update
    @business = Business.find(params[:id])
    if @business.update(business_params)
      redirect_to @business
    else
      render 'edit'
    end
  end

  def delete
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to businesses
  end

  def edit
    @business = Business.find(params[:id])
  end

  def new_connection
    @businesses = Business.all
    @business = Business.find(params[:id])
    @products = @business.products
  end

  def filter_new_connection
    @business = Business.find(params[:business_id])
    @products = @business.products
    respond_to do |format|
        format.html { redirect_to business_connection_path(business_id: params[:business_id]) }
        format.js
      end
  end

  def business_params
    params.require(:business).permit(:location, :name, :description, :logo, :business_category_id)
  end
end

app/views/businesses/_form.html.erb
<div class="card-body">
    <%= simple_form_for @business do |f| %>
    <%= f.input :name %>
    <%= f.input :business_category, collection: BusinessCategory.all, selected: @business.business_category.id %>
    <%= f.input :location %>
    <%= f.input :description %>
    <%= f.input :logo, label: "Change Logo" %>
    <%= f.input :logo_cache, as: :hidden %>
    <%= f.button :submit, class: 'btn btn-primary edit-button', value: 'Update Business' %>
    <% end %>
</div>

app/views/businesses/edit.html.erb
<div id="wrapper" name="page-top">
  <div class="d-flex flex-column" id="content-wrapper">
    <div id="content">
      <div class="container-fluid">
        <h3 class="text-dark mb-4">Edit my Business Details</h3>
        <div class="row mb-3">
          <div class="col-lg-4">
            <div class="card mb-3">
              <div class="card-body text-center shadow">

                <!--<img class="rounded-circle mb-3 mt-4" src="https://scontent.fjog1-1.fna.fbcdn.net/v/t1.0-9/53121420_157141011864141_7733435971928064000_n.png?_nc_cat=107&amp;_nc_oc=AQkDPscvlPqt8x91rV4VlttdfDPqL2jcrJwMAxsk3zuZGItxdDfzX_VdpIJTMvWVCxY&amp;_nc_ht=scontent.fjog1-1.fna&amp;oh=c78dc92a9e7a3bc742333f744f690884&amp;oe=5DDF1C63"-->
                <!--  width="160" height="160" alt="Business.logo">-->
              <% if !@business.logo.blank? %>
                <%= cl_image_tag( @business.logo, class: 'rounded-circle mb-3 mt-4', height: 300, width: 300) %>
              <% else %>
                <%= cl_image_tag("npuoiegpmbgsbwcpy0hh", class: 'rounded-circle mb-3 mt-4', height: 300, width: 300) %>
              <% end %>

                <div class="mb-3">
                </div>
              </div>
            </div>

          </div>
          <div class="col-lg-8">
            <div class="row mb-3 d-none">
              <div class="col">
                <div class="card text-white bg-primary shadow">
                  <div class="card-body">
                    <div class="row mb-2">
                      <div class="col">
                        <p class="m-0">Peformance</p>
                        <p class="m-0"><strong>65.2%</strong></p>
                      </div>
                      <div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
                    </div>
                    <p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last month</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card text-white bg-success shadow">
                  <div class="card-body">
                    <div class="row mb-2">
                      <div class="col">
                        <p class="m-0">Peformance</p>
                        <p class="m-0"><strong>65.2%</strong></p>
                      </div>
                      <div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
                    </div>
                    <p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last month</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="card shadow mb-3">
                  <div class="card-header py-3">
                    <p class="text-primary m-0 font-weight-bold">Business Information</p>
                  </div>
                  <div class="card-body">

                    <%= simple_form_for @business do |f| %>
                      <%= f.input :name %>
                      <%= f.input :business_category, collection: BusinessCategory.all, selected: @business.business_category.id %>
                      <%= f.input :location %>
                      <%= f.input :description %>
                      <%= f.input :logo, label: "Change Logo" %>
                      <%= f.input :logo_cache, as: :hidden %>
                      <%= f.button :submit, class: 'btn btn-primary edit-button', value: 'Update Business' %>
                    <% end %>

                  </div>
                </div>
                <div class="card shadow"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a></div>

app/views/businesses/filter_new_connection.js.erb
document.querySelector("#products").innerHTML = "";
document.querySelector("#products").insertAdjacentHTML("afterbegin", "<%= j render 'products/product', products: @products %>");

app/views/businesses/index.html.erb
<section class="clean-block clean-catalog dark">
<div class="container">
  <div class="block-heading">
    <h2 class="text-info">Member businesses</h2>
  </div>

  <div class="content">
    <div class="products pl-5 card-grid-3c">
      <% @businesses.each do |business| %>
        <div>
          <%= link_to business_path(business.id) do %>
          <%= business.name %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</section>

app/views/businesses/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Add your business to Czekpass!</h1>

      <%= simple_form_for [@business] do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :logo %>
        <%= f.association :business_category %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/businesses/new_connection.html.erb
<div class="viewport-wrapper">
 <div class="container">
  <div class="pb-2 px-4 pt-3">
     <h1>Add a partner</h1>
     <p>Select the business whose customer you want to give perks to:</p>

    <%= form_with(url: filter_business_connection_path, method: :get, id: 'business-select', class: 'form-group') do |f| %>

      <%= select_tag(:business_id, options_from_collection_for_select(Business.all, :id, :name ), class: 'form-control-lg w-100')%>
    <% end %>
  </div>
</div>

<div id="products"></div>

<h1><%=  %></h1>
 <script>
  const selects = document.querySelector('#business-select select');

  document.addEventListener("DOMContentLoaded", () => {
    selects.value = <%= params[:bid] %>
    Rails.fire(document.querySelector('#business-select'), "submit" )
  });
  selects.addEventListener("change", () => {
    // this is not working... why?
    console.log(document.location.search)
    Rails.fire(document.querySelector('#business-select'), "submit" )
  })
 </script>

app/views/businesses/show.html.erb
<div id="wrapper">
<div id="content-wrapper" class="d-flex flex-column">
<div id="content">
<div class="container-fluid">

  <div class="d-flex business-info">
    <div class="business-logo">
      <% if @business.logo.present? %>
        <%= cl_image_tag @business.logo, height: 140, width: 140 %>
      <% else %>
        <%= image_tag "https://previews.123rf.com/images/urfandadashov/urfandadashov1808/urfandadashov180801065/106295283-placeholder-company-logo-design-template-placeholder-logotype-vector-icon-business-corporative.jpg", height: 140, width: 140 %>
      <% end %>
    </div>
    <div class="business-description col-8">
      <div>
        <h5><%= @business.name %></h5>
        <%= @business.description %>
        <%= @business.location %>
      </div>
      <% if current_user.business == Business.find(params[:id]) %>
        <%= link_to "edit", edit_business_path, class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </div>

  <!-- Tabbed view -->
  <div class="row mt-4">
    <div class="col-lg-12 mb-4">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
        <nav>
          <div class="nav nav-tabs  nav-fill" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-perks" role="tab" aria-controls="nav-home" aria-selected="true">Perks</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-products" role="tab" aria-controls="nav-profile" aria-selected="false">Products</a>
          </div>
        </nav>
        </div>

        <div class="card-body">
          <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-perks" role="tabpanel" aria-labelledby="nav-home-tab">
              <div class="grid-view ">
                <% @user.perks(@business).each_with_index do |perk, index| %>

                    <%= render partial: 'shared/perk_card', locals: {perk: perk, index: index} %>

                <% end %>
              </div>
            </div>
            <div class="tab-pane fade" id="nav-products" role="tabpanel" aria-labelledby="nav-profile-tab">
              <div class="grid-view">
                <% @business.products.each_with_index do |product, index| %>

                    <%= render partial: 'shared/product_card', locals: {product: product, index: index} %>

                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</div>