config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'

  resources :businesses do
    resources :employees
    resources :perks, only: [:new, :create]
    resources :products do
      resources :perks, only: [:show, :new, :edit, :update, :destroy]
    end
    resources :perk_templates, only: [:new, :create]
  end

  resources :users, except: [:new, :create, :index, :show]

  resources :purchases, except: [:edit, :update, :destroy]

  get 'users/:id/validate', to: 'users#validate', as: 'validation_page'
  get 'discover', to: 'pages#discover'

  get 'business_dashboard', to: 'pages#business_dashboard', as: 'business_dashboard'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard_page'

  get 'welcome', to: 'pages#welcome', as: 'welcome_page'

  get 'businesses/:id/new_connection', to: 'businesses#new_connection', as: 'business_connection'

  get 'businesses/:id/filter_new_connection', to: 'businesses#filter_new_connection', as: 'filter_business_connection'


end

app/views/shared/_blank_page.html.erb
<div class="container-fluid">
  <h3 class="text-dark mb-1">Blank Page</h3>
</div>

app/views/shared/_business_card.html.erb
<div class="card">
   <div class="card-header">
      <%= link_to business.name, business_path(business.id)%>
  </div>
  <div class="d-flex p-3">
      <div>
        <% if business.logo.present? %>
          <%= cl_image_tag business.logo, height: 140, width: 140 %>
        <% else %>
          <%= image_tag "https://previews.123rf.com/images/urfandadashov/urfandadashov1808/urfandadashov180801065/106295283-placeholder-company-logo-design-template-placeholder-logotype-vector-icon-business-corporative.jpg", height: 140, width: 140 %>
        <% end %>
      </div>

      <div class="ml-3 align-items-center">
        <%= business.description.capitalize.slice(0, 100) %>...
        <div>
          <%= link_to business_path(business.id) do %>
            <%= current_user.perks(business).count %> perk available
          <% end %>
        </div>

      </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white sticky-footer">
  <div class="container my-auto">
    <div class="text-center my-auto copyright"><span>Copyright © czekpass 2019</span></div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion toggled bg-gradient-primary p-0">
  <div class="container-fluid d-flex flex-column p-0">
    <!--<a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href=" ">-->
      <%= link_to root_path, class: "navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" do %>
        <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-check-double"></i>
        </div>
      <div class="sidebar-brand-text mx-3"><span>czekpass</span>
      </div>
      <% end %>
    </a>
    <hr class="sidebar-divider my-0">
    <ul class="nav navbar-nav text-light" id="accordionSidebar">
      <% if current_user.admin %>
      <li class="nav-item" role="presentation">

        <a class="nav-link" href="/dashboard.html"><i class="fas fa-tachometer-alt"></i><span>User Dashboard</span></a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" href="/business_dashboard.html"><i class="fas fa-tachometer-alt"></i><span>Business Dashboard</span></a>
      </li>

      <li class="nav-item" role="presentation">

      <a class="nav-link" href="/businesses/<%= current_user.business.id %>/products/new">Create Product</a>
      </li>

      <%
=begin%>
 <li class="nav-item" role="presentation"><a class="nav-link" href="/businesses/<%= current_user.business.id %>/perks/new">Create Perk</a>
<%
=end%>

        </li>
      <li class="nav-item" role="presentation"><a class="nav-link" href="#">Verified Purchase</a></li>
      <li class="nav-item" role="presentation"><a class="nav-link" href="#">Non-Verified Purchase</a></li>

      <% else %>
            <li class="nav-item" role="presentation">
        <a class="nav-link" href="/dashboard"><i class="fas fa-tachometer-alt"></i><span>User Dashboard</span></a>
      </li>
      <% end %>
      <li class="nav-item" role="presentation"></li>
    </ul>
    <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
  </div>
</nav>
<div class="d-flex flex-column" id="content-wrapper">
  <div id="content">
    <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
      <div class="container-fluid">
        <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
        <% unless current_page?(discover_path) or current_page?(dashboard_page_path) or current_page?(business_dashboard_path) %>
          <%= link_to 'Back', :back, class: 'btn btn-info' %>
        <% end %>
        <ul class="nav navbar-nav flex-nowrap ml-auto">
          <!--<li class="nav-item dropdown d-sm-none no-arrow"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#"><i class="fas fa-search"></i></a>-->

          <li class="nav-item dropdown no-arrow mx-1" role="presentation">
            <li class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#"><span class="badge badge-danger badge-counter">3+</span><i class="fas fa-bell fa-fw"></i></a>
              <div class="dropdown-menu dropdown-menu-right dropdown-list dropdown-menu-right animated--grow-in" role="menu">
                <h6 class="dropdown-header">NEW PERKS AVILABLE!</h6>
                <a class="d-flex align-items-center dropdown-item" href="#">
                  <div class="mr-3">
                    <div class="bg-primary icon-circle"><i class="fas fa-file-alt text-white"></i></div>
                  </div>
                  <div><span class="small text-gray-500">December 12, 2019</span>
                    <p>20% at Body Factory!</p>
                  </div>
                </a>
                <a class="d-flex align-items-center dropdown-item" href="#">
                  <div class="mr-3">
                    <div class="bg-success icon-circle"><i class="fas fa-donate text-white"></i></div>
                  </div>
                  <div><span class="small text-gray-500">December 7, 2019</span>
                    <p>Free Coffee at Motion Cafe!</p>
                  </div>
                </a>
                <a class="d-flex align-items-center dropdown-item" href="#">
                  <div class="mr-3">
                    <div class="bg-warning icon-circle"><i class="fas fa-exclamation-triangle text-white"></i></div>
                  </div>
                  <div><span class="small text-gray-500">December 2, 2019</span>
                    <p>10% at LeWagon</p>
                  </div>
                </a><a class="text-center dropdown-item small text-gray-500" href="#">Show All Alerts</a></div>
            </li>
          </li>
          <div class="d-none d-sm-block topbar-divider"></div>
          <li class="nav-item dropdown no-arrow" role="presentation">
            <li class="nav-item dropdown no-arrow">
              <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">
                <span class="d-none d-lg-inline mr-2 text-gray-600 small"><%= current_user.full_name %>
                </span>

                <% if current_user && current_user.photo.present? %>
                  <%= cl_image_tag current_user.photo, width: 40, height: 40, crop: :thumb, gravity: :face, class: 'avatar', alt: "user photo" %>
                <% else %>
                  <img class="border rounded-circle img-profile" src="https://www.belr.com/wp-content/uploads/2017/06/avatar-placeholder-generic-1.jpg">
                <% end %>
              </a>

            <!-- Avatar and dropdown menu items -->

              <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in" role="menu">
                <%= link_to dashboard_page_path, class: "dropdown-item", role: "presentation"  do%>
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>Profile
                <% end %>
                <%= link_to discover_path, class: "dropdown-item", role: "presentation"  do%>
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i> Perks
                <% end %>



              <% if current_user.business.present? and current_page?(business_dashboard_path) == false %>


                <%= link_to business_dashboard_path, class: 'dropdown-item', role: "presentation" do %>
                  <i class="fas fa-user-tie fa-sm fa-fw mr-2 text-gray-400"></i>Switch to Business View
                <% end %>

              <% elsif current_user.business.present? %>
                <%= link_to discover_path, class: 'dropdown-item' do %>
                      <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>Switch to Customer View</span>
            <% end %>
            <% elsif current_user.business.present? == false %>
              <%= link_to new_business_path, class: 'dropdown-item' do %>
                <i class="fas fa-store-alt fa-sm fa-fw mr-2 text-gray-400"></i>Add a business
              <% end %>
            <% end %>










                <div class="dropdown-divider"></div>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item", role: "presentation"  do%>
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>Logout
                <% end %>
              </div>
            </li>
          </li>
        </ul>
      </div>
    </nav>
<!--
<script>
  const businessNav = document.getElementById('business-nav');
  const businessNavNest = document.getElementById('business-nav-nest');
  console.log(businessNav)
  businessNav.addEventListener('mouseover', (e) => {
    businessNavNest.classList.toggle('d-none');
  });

</script> -->
<style>
  @media only screen and (min-width: 1024px) {
    #business-nav-nest {
      opacity: 0;
    }

    #business-nav:hover ~ #business-nav-nest {
      opacity: 1;
      transition: all 1s ease;
    }
  }
</style>

app/views/shared/_perk_card.html.erb
<div class="card bg-light">

<div class="p-3">

<%= tag.a aria: {expanded: "false", controls: "collapseExample#{index}"}, href: "#collapseExample#{index}", role: "button", data: {toggle: "collapse"} do %>
  <h6 class="m-0 font-weight-bold text-primary">
    <% if perk.kind == "percentage" %>
      <%= perk.amount %> % off
    <% elsif perk.kind == "amount" %>
      <%= perk.amount %> $ off
    <% else %>
      Free
    <% end %>
    <%= perk.product.name %></h6>
<% end %>


  <%= tag.div class: 'collapse p-4', id: "collapseExample#{index}" do%>
    <%= render partial:  'perks/perk_show', locals: {perk: perk}%>
  <% end %>

  <div>
    <span class="discounted-initial-price">
      <%= humanized_money_with_symbol(perk.product.price) %>
    </span>
  </div>
</div>
</div>

app/views/shared/_product_card.html.erb
<!-- <div class="card-product custom-card"> -->

<div class="card align-content-between">

  <div class="photo">
    <p><%= product.photo %></p>
  </div>
  <div class="card-product-infos p-3">

<%= tag.a aria: {expanded: "false", controls: "collapseExample#{index}"}, href: "#collapseExample#{index}", role: "button", data: {toggle: "collapse"} do %>
    <%= product.name %>
<% end %>


    <%= tag.div class: 'collapse p-4', id: "collapseExample#{index}" do%>
      <%= render partial: 'products/product_show', locals: {product: product}%>
    <% end %>

    <p><%= humanized_money_with_symbol(product.price) %></p>
  </div>
</div>

app/views/shared/_purchase_card.html.erb
<div class="card">

  <div class="">
    <div class="p-3 purchase-card-content bg-light">
      <div>
        <strong>Purchase date:</strong> <%= purchase.creation.strftime("%B %d, %Y") %>
        <div>
          <h6 class="m-0 font-weight-bold text-primary">
          <%= link_to purchase.product.business.name, business_path(purchase.product.business) %>
          </h6>
        </div>
          <%= purchase.product.name %>
      </div>

      <div><%= purchase.product.description %></div>

      <%# purchase.product.perks.each do |perk| %>
        <!-- <p class="border p-2">Unlocked Perk:  <%#= link_to perk.description, business_product_perk_path(purchase.product.business, purchase.product, perk) %></p> -->
      <%# end %>

      Price: <%= humanized_money_with_symbol(purchase.product.price) %>
    </div>

    <div class="card-footer align-self-baseline bg-white border-left-success">
      Perk Expiration date:
      <% if purchase.expiration_date %>
        <strong><%= purchase.expiration_date.strftime("%B %d, %Y") %></strong>
      <% else %>
        <strong><%= purchase.creation.strftime("%B %d, %Y") %></strong>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_saving_card.html.erb
<div class="saving-card">
  <div class="form-time">
    View how much you've saved for:
    <form action="/dashboard" id="time-form" data-remote="true">
      <select name="saving">
        <option value="7">This week</option>
        <option value="30">This month</option>
        <option value="90">Last 3 months</option>
      </select>
    </form>
  </div>

  <% if saving_dollars_amount.nil? %>
  You have no savings! Get busy!
  <% else %>
  <p>Your total savings to date are: $<%= saving_dollars_amount + discounted_price_total %></p>
  <p id="total-timed-savings">Your savings for the selected period of time are: $<%= total_saving %></p>
  <% end %>
</div>