config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'

  resources :businesses do
    resources :employees
    resources :perks, only: [:new, :create]
    resources :products do
      resources :perks, only: [:show, :new, :edit, :update, :destroy]
    end
    resources :perk_templates, only: [:new, :create]
  end

  resources :users, except: [:new, :create, :index, :show]

  resources :purchases, except: [:edit, :update, :destroy]

  get 'users/:id/validate', to: 'users#validate', as: 'validation_page'
  get 'discover', to: 'pages#discover'

  get 'business_dashboard', to: 'pages#business_dashboard', as: 'business_dashboard'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard_page'

  get 'welcome', to: 'pages#welcome', as: 'welcome_page'

  get 'businesses/:id/new_connection', to: 'businesses#new_connection', as: 'business_connection'

  get 'businesses/:id/filter_new_connection', to: 'businesses#filter_new_connection', as: 'filter_business_connection'


end

app/views/pages/_info_window.html.erb
<%= link_to business_path(businesses.id) do %>
  <div class="container">
    <div><%= businesses.name %></div>
    <div><%= businesses.location %></div>
  </div>
<% end %>

app/views/pages/business_dashboardold.html.erb
<div class="container">

<!-- <= link_to "edit", edit_business_path %> -->

<!-- For the show If current_user = @Business.user then show edit form(partial) else show business_card partial-->

<%= link_to "My business", business_path(current_user.business) %>

<div id="wrapper" name="page-top">
  <div class="d-flex flex-column" id="content-wrapper">
    <div id="content">
      <div class="container-fluid">
        <h3 class="text-dark mb-4">Edit my Business Details</h3>
        <div class="row mb-3">
          <div class="col-lg-4">
            <div class="card mb-3">
              <div class="card-body text-center shadow">

                <!--<img class="rounded-circle mb-3 mt-4" src="https://scontent.fjog1-1.fna.fbcdn.net/v/t1.0-9/53121420_157141011864141_7733435971928064000_n.png?_nc_cat=107&amp;_nc_oc=AQkDPscvlPqt8x91rV4VlttdfDPqL2jcrJwMAxsk3zuZGItxdDfzX_VdpIJTMvWVCxY&amp;_nc_ht=scontent.fjog1-1.fna&amp;oh=c78dc92a9e7a3bc742333f744f690884&amp;oe=5DDF1C63"-->
                <!--  width="160" height="160" alt="Business.logo">-->
              <% if !@business.logo.blank? %>
                <%= cl_image_tag( @business.logo, class: 'rounded-circle mb-3 mt-4') %>
              <% else %>
                <%= cl_image_tag("npuoiegpmbgsbwcpy0hh", class: 'rounded-circle mb-3 mt-4') %>
              <% end %>

                <div class="mb-3">
                </div>
              </div>
            </div>
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="text-primary font-weight-bold m-0">Perk Usage</h6>
              </div>
              <div class="card-body">
                <h4 class="small font-weight-bold">LeWagon - 1 Month<span class="float-right">20%</span></h4>
                <div class="progress progress-sm mb-3">
                  <div class="progress-bar bg-danger" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;"><span class="sr-only">20%</span></div>
                </div>
                <h4 class="small font-weight-bold">Motion Cafe - 3 Months<span class="float-right">40%</span></h4>
                <div class="progress progress-sm mb-3">
                  <div class="progress-bar bg-warning" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"><span class="sr-only">40%</span></div>
                </div>
                <h4 class="small font-weight-bold">Nude - 1 Day<span class="float-right">60%</span></h4>
                <div class="progress progress-sm mb-3">
                  <div class="progress-bar bg-primary" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"><span class="sr-only">60%</span></div>
                </div>
                <h4 class="small font-weight-bold">Perk Savings<span class="float-right">$8040.33</span></h4>
                <div class="progress progress-sm mb-3">
                  <div class="progress-bar bg-info" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;"><span class="sr-only">80%</span></div>
                </div>
                <h4 class="small font-weight-bold">Added Product Value<span class="float-right">12%</span></h4>
                <div class="progress progress-sm mb-3">
                  <div class="progress-bar bg-success" aria-valuenow="12" aria-valuemin="0" aria-valuemax="100" style="width: 12%;"><span class="sr-only">12%</span></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-8">
            <div class="row mb-3 d-none">
              <div class="col">
                <div class="card text-white bg-primary shadow">
                  <div class="card-body">
                    <div class="row mb-2">
                      <div class="col">
                        <p class="m-0">Peformance</p>
                        <p class="m-0"><strong>65.2%</strong></p>
                      </div>
                      <div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
                    </div>
                    <p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last month</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card text-white bg-success shadow">
                  <div class="card-body">
                    <div class="row mb-2">
                      <div class="col">
                        <p class="m-0">Peformance</p>
                        <p class="m-0"><strong>65.2%</strong></p>
                      </div>
                      <div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
                    </div>
                    <p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last month</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="card shadow mb-3">
                  <div class="card-header py-3">
                    <p class="text-primary m-0 font-weight-bold">Business Information</p>
                  </div>
                  <div class="card-body">
                    <%= simple_form_for @business do |f| %>
                      <%= f.input :name %>
                      <%= f.input :business_category, collection: BusinessCategory.all, selected: @business.business_category.id %>
                      <%= f.input :location %>
                      <%= f.input :description %>
                      <%= f.input :logo, label: "Change Logo" %>
                      <%= f.input :logo_cache, as: :hidden %>
                      <%= f.button :submit, class: 'btn btn-primary edit-button', value: 'Update Business' %>
                    <% end %>

                  </div>
                </div>
                <div class="card shadow"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a></div>

app/views/pages/dashboard.html.erb
<div class="user-profile-header pl-3 mb-3">

  <div class="d-flex">
    <div>
      <%= cl_image_tag current_user.photo, width: 90, height: 90, crop: :thumb, gravity: :face, class: 'avatar-huge', alt: "user photo" %>
    </div>

    <div class="ml-3">
      <h1>Hello <%= @user.first_name %>!</h1>
      <div>
        <%= link_to 'Edit your profile', edit_user_path(current_user) %>
      </div>
    </div>
  </div>

  <%# if current_user.business.nil? == false%>
    <%#= link_to 'Add your business', new_business_path(current_user) %>
    <!-- <br> -->
    <%#= link_to 'View your business dashboard', business_dashboard_path(current_user) %>
    <!-- <br> -->
  <%# end %>

</div>
<div class="p-3">
  <div class="card">
    <nav>
      <div class="nav nav-tabs nav-pills nav-fill bg-light sticky" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Savings</a>
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Perks</a>
        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Purchases</a>
      </div>
    </nav>

    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active bg-white" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <%= render partial: 'shared/saving_card', locals: { saving_dollars_amount: @saving_dollars_amount, discounted_price_total: @discounted_price_total, total_saving: @total_saving } %>
      <!--     <p>In the past week you have saved: <%#= @weekly_savings %>$!</p>
      <p>In the past month you have saved: <%#= @monthly_savings %>$!</p>-->
      </div>

      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
        <div class="grid-view">
          <% @user.perks.each_with_index do |perk, index| %>
            <%= render partial: 'shared/perk_card', locals: {perk: perk, index: index} %>
          <% end %>
        </div>
      </div>

      <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
        <div class="grid-view">
        <% @user.purchases.each do |purchase| %>
            <%= render partial: 'shared/purchase_card', locals: {purchase: purchase} %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.js.erb
// 1. figure out what you want to do on search
// We want to change the total amount saved for that period.
// 2. select the element that updates and store in variable
  // 3. document.querySelector('#total-savings')
// 4. Change the innerText to be @total_saving
// 5. You can use JS and ERB in this file, check Kitt for example


function refreshTimedSavings(total_saving) {
  const newTimeForm = document.getElementById('total-timed-savings');
  newTimeForm.innerText = total_saving;
}

refreshTimedSavings('Your total savings for this time are: $<%= @total_saving %>');

app/views/pages/discover.html.erb
  <div class="px-4">
  <div class="page-header bg-light mb-4">
    <h3>Perks near you</h3>
  </div>

  <!-- This should be a form -->
  <div class="form-row no-gutters">
    <div class="form-group flex-grow-1">

    <!-- This is the first half -->
        <%= form_tag discover_path, method: :get, class: 'flex-grow-1' do %>
            <div class="input-group">
              <button class="btn btn-secondary filter-button" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                <i class="fas fa-filter"></i>
              </button>
              <div class="input-group-prepend loc-button">
                   <button class="btn bg-white" name="coords" type="button" id="loc"><i class="fas fa-crosshairs"></i></button>
              </div>
              <%= text_field_tag :query,
                params[:query],
                class: "form-control pl-1",
                placeholder: "Search for business"
              %>
              <div class="input-group-append">
                <%= submit_tag "Search", class: "btn btn-primary" %>
              </div>
            </div>
        <% end %>
    </div>

    <!-- This is the second half -->
    <div class="form-group">

    </div>
  </div>

  <!-- This is the filters -->

  <div id="formFilters"></div>
    <div class="collapse" id="collapseExample">
          <h3>Categories:</h3>
      <div class="container filter-container">
        <!-- Used this to make cards for all business categories(not location specific) -->
        <%# @businesses = Business.all %>

        <% @all_businesses = Business.near('Canggu', 10) %>
        <!-- Iterating through all businesses near Canggu -->
          <% @all_businesses.each do |business| %>
        <div class="row">
            <div class="filter-card d-inline text-white m-2 p-3">
        <!-- putting the categories of businesses near me -->
        <%= link_to business_path(business.id) do %>
                <%= business.business_category.name %>
                <% end %>
            </div>
        </div>
          <% end %>
      </div>
    </div>
  </div>
  <nav>
    <div class="nav nav-tabs  nav-fill" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-map-tab" data-toggle="tab" href="#nav-map" role="tab" aria-controls="nav-map" aria-selected="true">Map</a>
      <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">List</a>
    </div>
  </nav>

    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-map" role="tabpanel" aria-labelledby="nav-map-tab">
        <div
          id="map"
          style="width: 100%;
          height: 100%;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>
      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
          <div class="container my-4">
          <div class="grid-view">
              <% @businesses.each do |business| %>
                    <%= render partial: 'shared/business_card', locals: {business: business} %>
              <% end %>
            </div>
          </div>
      </div>
    </div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

Hello, is this the right page?

app/views/pages/search.js.erb
$('#results_div').html("<%= j @results.pluck(:title).join('<br/>') %>")

app/views/pages/welcome.html.erb
<!-- Proper implementation method to follow -->
<!-- So make it right, link to it after a new user is made with devise...how?  Then link to right things within. -->
<!-- Welcome them with proper welcome message. -->
<!-- Prompt link to user discovery/dashboard to see what's available around them -->
<!-- Prompt to register their new business to proper page if they are a business owner -->
<!-- Footer/header? -->

<div class="container">
<h1>Welcome to Czekpass!</h1>


<p>If you would like to explore the available businesses and perks around you, please click here:</p>
<p> <%=  link_to "Explore", discover_path%> </p>

<p>If you would like to sign your business up to Czekpass, please click here:</p>
<p> <%= link_to "Register your business", new_business_path %> </p>
</div>