config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'

  resources :businesses do
    resources :employees
    resources :perks, only: [:new, :create]
    resources :products do
      resources :perks, only: [:show, :new, :edit, :update, :destroy]
    end
    resources :perk_templates, only: [:new, :create]
  end

  resources :users, except: [:new, :create, :index, :show]

  resources :purchases, except: [:edit, :update, :destroy]

  get 'users/:id/validate', to: 'users#validate', as: 'validation_page'
  get 'discover', to: 'pages#discover'

  get 'business_dashboard', to: 'pages#business_dashboard', as: 'business_dashboard'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard_page'

  get 'welcome', to: 'pages#welcome', as: 'welcome_page'

  get 'businesses/:id/new_connection', to: 'businesses#new_connection', as: 'business_connection'

  get 'businesses/:id/filter_new_connection', to: 'businesses#filter_new_connection', as: 'filter_business_connection'


end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents
  belongs_to :business
  mount_uploader :photo, PhotoUploader

  # I don't understand these validations.
  # has_many :providing_products, foreign_key: "providing_product_id", class_name: "Perk"
  # has_many :receiving_products, foreign_key: "receiving_product_id", class_name: "Perk"
  has_many :purchases

  has_many :perks, foreign_key: "product_id", class_name: "Perk"

  validates :name, presence: true
  validates :description, presence: true
  validates :price_cents, presence: true
  validates :category, presence: true

  def purchased_in_the_last_month
     purchases = Purchase.where(verified: true, product_id: self.id)
     purchases.where("created_at >= ?", Date.today - 30)
  end

  def purchased_in_the_last_year
     purchases = Purchase.where(verified: true, product_id: self.id)
     purchases.where("created_at >= ?", Date.today - 365)
  end

  def top_partner

  end

  def activated_perks
    perks = self.perks
    results = []
    perks.each do |perk|
      info = {}
      total_activations = 0
      total_price = 0
      connected_purchase = Purchase.where(product_id: perk.product_id)
      count = connected_purchase.count
      info[:description] = perk.description
      info[:count] = count
      connected_purchase.each do |connected|
        total_activations += 1 if connected.verified?
        total_price += (self.price_cents / 100) - perk.discounted_price if connected.verified?
        # total_price = total_price - perk.discounted_price
      end
      info[:total_activations] = total_activations
      info[:total_price] = total_price
      results << info
     end
     results
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @business = Business.find(params[:business_id])
    @products = @business.products
  end

  def new
    @business = Business.find(params[:business_id])
    @product = Product.new
  end

  def show
    @business = Business.find(params[:business_id])
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    @business = Business.find(params[:business_id])
    @product.business = @business
    if @product.save
      redirect_to business_dashboard_path
    else
      render :new
    end
  end


  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to business_dashboard_path #get from rails routes
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to business_dashboard_path
  end

  def edit
    @product = Product.find(params[:id])
    @business = Business.find(params[:business_id])
  end


  # def price
  #   @product = Product.find(params[:id])
  #   @product.price
  # end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :category, :photo)
  end
end

app/views/products/_product.html.erb
<div class="container">
  <div class="container px-4 pb-4 mb-5">

  <%= simple_form_for Perk.new, url: business_perks_path(params[:id]) do |f| %>

      <% products.each do |product| %>

      <!-- Product / Perk card -->
      <div class="px-3">
        <!-- Product part -->
        <div class="bg-light p-4 shadow-sm rounded product-perk-card-parent">
          <h4><%= product.name %></h4>

          <div>
            <div class="product-photo">

            </div>
            <div>
              <p><%= product.description %></p>
            </div>
          </div>

        </div>

        <div class="bg-white shadow-sm p-3 rounded product-perk-card">

           <div>

        <!-- Card -->
        <!-- First row -->
        <span style="margin-left: -4px">
          <strong>Purchasing this product unlocks a perk for: </strong>
        </span>

          <div class="form-row p-2 border-left">

            <%= f.input :purchased_product_id, as: :hidden, input_html: {name: "perk[][purchased_product_id]", value: product.id} %>
            <%= f.input :patronized_business_id, as: :hidden, input_html: {name: "perk[][patronized_business_id]", value: product.business.id} %>

            <!-- Product the perk applies to -->
            <div class="w-100">
              <%= f.input :product_id, as: :select, collection: Product.where(business_id: params[:id]), label: false, input_html: {name: "perk[][product_id]", class:'mb-0 custom-select'} %>
            </div>
            </div>
            <div class="form-row border-left p-2">
              <p class="m-0 p-0 w-100">Perk</p>
              <select class="custom-select col-9" name="perk[][kind]">
                  <option ></option>
                  <option value="free" class="dropdown-item">Free</option>
                  <option value="percentage" class="dropdown-item">Percentage</option>
                  <option value="amount" class="dropdown-item">Amount</option>
                </select>

              <input type="number" name="perk[][amount]" class="col-3 form-control" value="0">
            </div>
          </div>

        <!-- Second row -->
          <div class="form-row border-left px-2">
            <label for="Description">Description</label>
            <textarea class="form-control" id="Description" rows="2" name="perk[][description]"></textarea>
          </div>

        </div>

      </div>
      <% end %>

    <%= f.submit "Save", class: 'btn btn-primary w-50 float-right mb-4' %>

    </div>

  <% end %>

  </div>
</div>
</div> <!-- This is the end div for the viewport wrapper -->

app/views/products/_product_show.html.erb
  <div><%= product.name %></div>
  <div><%= product.description %></div>
  <div><%= product.category %></div>
  <div><%= product.photo %></div>

app/views/products/edit.html.erb
<div class="container">
  <h1>Edit your product</h1>
  <%= simple_form_for [@business, @product] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :price_cents %>
  <%= f.submit class: 'btn btn-primary' %>
  <% end %>
  <%= link_to "Delete this product", business_product_path, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/products/index.html.erb
<section class="clean-block clean-catalog dark">
  <div class="container">
    <div class="block-heading">
      <h2 class="text-info">Your </h2>
    </div>

    <div class="content">
      <div class="products pl-5 card-grid-3c">
       <% @products.each do |product| %>
         <%= link_to product.name, edit_business_product_path(product.business, product) %>
      <% end %>
    </div>
  </div>
</div>
</section>

app/views/products/new.html.erb
<div id="wrapper">
  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
      <!-- Begin Page Content -->
      <div class="container-fluid">

        <!-- Content Row -->
        <div class="row">
          <div class="col-12">
            <div class="card mb-4">
            
              <div class="card-body">
                <div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new product for your business</h1>

      <%= simple_form_for [@business, @product] do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :category %>
        <%= f.input :photo %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
Show perks here.

<div class="container">
<%= @product.name %>
<ul>
  <li><%= @product.name %></li>
  <li><%= @product.description %></li>
  <li><%= humanized_money_with_symbol(@product.price) %></li>
  <li><%= @product.category %></li>
  <li><%= @product.photo %></li>
</ul>

<h4>Perks tied to this product</h4>
<% @product.perks.each do |perk| %>
  <div class="perk-card">
    <% if perk.kind == "percentage" %>
      <%= "#{perk.amount} % off" %>
    <% elsif perk.kind == "amount" %>
    <!-- This needs to be refactored to adjust to any currency-->
      <%= "#{perk.amount} $ off" %>
    <% else %>
      Free
    <% end %>
     <%= link_to perk.purchased_product.name, business_product_perk_path(perk.purchased_product.business, perk.purchased_product, perk) %>

    <div><%= perk.description%></div>
    <div>
      <span class="discounted-initial-price">
        <%= humanized_money_with_symbol(perk.purchased_product.price) %>
      </span>
    </div>
  </div>>
<% end %>


<%= link_to "Edit", edit_business_product_path %>
<br>
<%= link_to "Add a perk",  new_business_product_perk_path(product_id:params[:id]) %>
</div>